name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Setup Docker Buildx (build multi-platform, optimize size)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Setup Node.js and test (optional but recommended)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies and test
        run: |
          yarn install --frozen-lockfile
          echo "✅ Dependencies installed successfully"

      # 5. Build & Push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          target: production
          tags: |
            chungdfly/tic-tac-toe:latest
            chungdfly/tic-tac-toe:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 6. Security scan with Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: chungdfly/tic-tac-toe:latest
          format: 'table'
          exit-code: '0'

      # 7. Clean up to save disk space
      - name: Clean up
        run: docker system prune -af

      # 8. Notify success
      - name: Notify build success
        if: success()
        run: |
          echo "🎉 Docker image built and pushed successfully!"
          echo "Image: chungdfly/tic-tac-toe:latest"
          echo "SHA: chungdfly/tic-tac-toe:${{ github.sha }}"
